name: Deploy bot
run-name: ${{ github.actor }} is deploying bot
on: [push]
jobs:
  Docker-build-and-push:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Docker build
        run: docker build . -t kateraawi/test-ci-cd:latest -t kateraawi/test-ci-cd:${{ github.sha }}
      - name: Docker push
        run: |
          docker login -u kateraawi -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push kateraawi/test-ci-cd:latest
          docker push kateraawi/test-ci-cd:${{ github.sha }}
  Deploy:
    runs-on: self-hosted
    steps:
      - name: Play ansible-playbook
        run: |
          source /home/user/ansible-venv/bin/activate
          ansible-playbook -i inventory.ini -e "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" playbook.yml
